# IMPORTING ALL THE NECESSARY LIBRARIES

In [1]:
import keras
from   keras.datasets import mnist
from   keras.models   import Model
from   keras.layers   import LSTM, Input, Dense, TimeDistributed

In [2]:
# Training parameters
batch_size = 32
num_classes = 10
epochs = 5

In [3]:
# embedded dimensions
row_hidden = 128
col_hidden = 128

In [4]:
# DIVIDE THE DATASET INTO TRAINING AND TESTING DATA
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

# Shape of the Datasets

In [5]:
print(X_train.shape)

(60000, 28, 28)


In [6]:
print(X_test.shape)

(10000, 28, 28)


In [7]:
print(X_train.shape[0])
print(X_test.shape[0])

60000
10000


# Reshaping the Datasets into 4-D Hierarchical form

In [10]:
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test  = X_test.reshape(X_test.shape[0], 28, 28, 1)

In [11]:
# convert the training and testing data into float form
X_train = X_train.astype('float32')
X_test  = X_test.astype('float32')

# Divide the training and testing data by 255
X_train = X_train / 255
X_test  = X_test / 255


print(X_train.shape[0])
print(X_test.shape[0])

60000
10000


In [12]:
print(X_train[:5])

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [13]:
print(X_test[:5])

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

# Convert the class vectors into binary class metrics

In [15]:
from tensorflow.keras.utils import to_categorical

Y_train = to_categorical(Y_train, num_classes)
print(Y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [16]:
Y_test = to_categorical(Y_test, num_classes)
print(Y_test)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [27]:
row, col, pixel = X_train.shape[1:]

In [28]:
x = Input(shape = (row, col, pixel))

In [29]:
print(x)

KerasTensor(type_spec=TensorSpec(shape=(None, 28, 28, 1), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'")


# LSTM RNN ALGORITHM

In [30]:
# Apply the LSTM Algorithm to all the encoded rows
encoded_rows = TimeDistributed(LSTM(row_hidden))(x)

# Apply LSTM Algorithm to all the columns of the encoded rows
encoded_cols = LSTM(col_hidden)(encoded_rows)

In [31]:
# Performing LSTM function on the dense layer
prediction = Dense(num_classes, activation = 'softmax')(encoded_cols)

In [33]:
# calling the RNN Model
model = Model(x, prediction)
print(model)

# COMPILE THE RNN MODEL

In [35]:
model.compile(optimizer = 'RMSprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# TRAIN THE RNN MODEL

In [36]:
model.fit(X_train, Y_train, epochs = epochs, batch_size = batch_size , verbose = 1, validation_data = (X_test, Y_test))

Epoch 1/5
1875/1875 [==============================] - 518s 275ms/step - loss: 0.4753 - accuracy: 0.8415 - val_loss: 0.1222 - val_accuracy: 0.9627
Epoch 2/5
1875/1875 [==============================] - 497s 265ms/step - loss: 0.1206 - accuracy: 0.9636 - val_loss: 0.0612 - val_accuracy: 0.9822
Epoch 3/5
1875/1875 [==============================] - 500s 267ms/step - loss: 0.0792 - accuracy: 0.9761 - val_loss: 0.0921 - val_accuracy: 0.9747
Epoch 4/5
1875/1875 [==============================] - 511s 273ms/step - loss: 0.0612 - accuracy: 0.9811 - val_loss: 0.0568 - val_accuracy: 0.9824
Epoch 5/5
1875/1875 [==============================] - 525s 280ms/step - loss: 0.0507 - accuracy: 0.9843 - val_loss: 0.0447 - val_accuracy: 0.9878


# EVALUATE THE LOSS AND ACCURACY OF RNN MODEL

In [ ]:
loss, accuracy = model.evaluate(X_test, Y_test, verbose = 0)
print("Loss of the model is:", loss)
print("Accuracy of the model is:", (accuracy * 100.0))