In [1]:
import numpy as np

In [2]:
arr = np.array([4,2,8,5,3,9,12,56])
print(arr)

[ 4  2  8  5  3  9 12 56]


In [3]:
# sort the array
print(np.sort(arr))

[ 2  3  4  5  8  9 12 56]


In [4]:
# serach the element from the array
print(np.searchsorted(arr,8))

5


In [5]:
# count the non-zero elements in the array
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])
print(arr1)

[  0 324 645  65   6   6   0   0   0 234]


In [6]:
print(np.count_nonzero(arr1))

6


In [8]:
# where = It tells at which indexes the elements are greater than zero
print(arr1)
print(np.where(arr1 > 0))

[  0 324 645  65   6   6   0   0   0 234]
(array([1, 2, 3, 4, 5, 9]),)


In [11]:
# extract all the elements from the array that are greater than 2
print(arr1)
print(np.extract(arr1 > 2, arr1))

# extract all the elements from the array that are greater than 300
print(np.extract(arr1 > 300, arr1))

[  0 324 645  65   6   6   0   0   0 234]
[324 645  65   6   6 234]
[324 645]


# Byte- Swapping

In [12]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [13]:
#byte-swapping =  It provides the byte value for all the elelemnst in the array
arr1.byteswap(True)

array([                   0,  4900197869555810304, -8862521116711714816,
        4683743612465315840,   432345564227567616,   432345564227567616,
                          0,                    0,                    0,
       -1585267068834414592])

In [23]:
# Dot Operations In Array
arr1 = np.random.randint([[2,3] , [4,5]])


In [24]:
arr2 = np.random.randint([[5,3] , [2,5]])

In [25]:
# Dot product of two arrays
print(arr1)
print(arr2)
print(np.dot(arr1, arr2))

[[1 0]
 [0 0]]
[[0 1]
 [1 0]]
[[0 1]
 [0 0]]


In [26]:
arr1@arr2

array([[0, 1],
       [0, 0]])