# NUMPY ARRAY : MATHEMATICS

# ADDITION

In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
print(np.sum(a))

15


In [3]:
a , b = 10, 20
print(np.sum([a,b]))

30


In [4]:
a,b,c,d = 10,20,30,40
print(np.sum([a,b,c,d]))

100


In [5]:
a,c,e, g = 90,30,60,80
print(np.sum([a,c,e,g]))

260


In [6]:
c = 10
d = 90
e = 120
print(np.sum([c,d,e]))

220


In [7]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [10]:
# addition of elements along the column
print(np.sum(a, axis = 0))

[4 6]


In [11]:
# addition of elements along the row
print(np.sum(a, axis = 1))

[3 7]


In [12]:
c = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print(c)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [13]:
# addition of elements along the row
print(np.sum(c, axis = 1))

[10 26 42]


In [14]:
# addition of elements alog the column
print(np.sum(c, axis = 0))

[15 18 21 24]


# SUBSTRACTION

In [16]:
import numpy as np
print(np.subtract(20,10))

10


In [17]:
x = 90
y = 13
print(np.subtract(x,y))

77


In [18]:
import numpy as np
print(np.subtract(80,6))

74


# MULTIPLICATION

In [19]:
import numpy as np
print(np.multiply(2,3))

6


In [20]:
print(np.multiply(4,5))

20


In [21]:
print(np.multiply(8,9))

72


# DIVISION

In [22]:
import numpy as np
print(np.divide(10,2))

5.0


In [23]:
a = np.array([2,4,6])
b = np.array([1,2,3])
print(np.divide(a,b))

[2. 2. 2.]


In [24]:
c = np.array([10,20,30,40,50])
d = np.array([1,2,3,4,5])
print(np.divide(c,d))

[10. 10. 10. 10. 10.]


# EXPONENT

In [28]:
# exponent value of a
print(np.exp(a))

# exponent value of b
print(np.exp(b))

# exponent value of c
print(np.exp(c))

# exponent value of d
print(np.exp(d))

[  7.3890561   54.59815003 403.42879349]
[ 2.71828183  7.3890561  20.08553692]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


# SQUARE ROOT

In [32]:
# square root of of a
print(np.sqrt(a))

# square root of b
print(np.sqrt(b))

# square root of c
print(np.sqrt(c))

# square root of d
print(np.sqrt(d))

[1.41421356 2.         2.44948974]
[1.         1.41421356 1.73205081]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[1.         1.41421356 1.73205081 2.         2.23606798]


# SIN VALUE

In [36]:
# sin value of a
print(np.sin(a))

# sin value of b
print(np.sin(b))

# sin value of c
print(np.sin(c))

# sin value of d
print(np.sin(d))

[ 0.90929743 -0.7568025  -0.2794155 ]
[0.84147098 0.90929743 0.14112001]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


# COS VALUE

In [40]:
# cos value of a
print(np.cos(a))

# cos value of b
print(np.cos(b))

# cos value of c
print(np.cos(c))

# cos value of d
print(np.cos(d))

[-0.41614684 -0.65364362  0.96017029]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


# LOG VALUE

In [44]:
# log value of a
print(np.log(a))

# log value of b
print(np.log(b))

# log value of c
print(np.log(c))

# log value of d
print(np.log(d))

[0.69314718 1.38629436 1.79175947]
[0.         0.69314718 1.09861229]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


# ARRAY COMPARISION

## 1. ELEMENT WISE ARRAY COMPARISION

In [45]:
a = np.array([1,2,4])
b = np.array([2,2,4])
c = np.array([1,2,4])

In [46]:
print(np.equal(a,b))

[False  True  True]


In [47]:
print(np.equal(b,c))

[False  True  True]


In [48]:
print(np.equal(a,c))

[ True  True  True]


## 2. ARRAY WISE ARRAY COMPARISION

In [49]:
print(np.array_equal(a,b))

False


In [50]:
print(np.array_equal(b,c))

False


In [52]:
print(np.array_equal(a,c))

True


# AGGREGRATE FUNCTIONS

In [78]:
a = np.array([1,2,4])
b = np.array([2,2,4])
c = np.array([1,2,4])

# sum of all the  elements in the array
print("Sum of all elements is:", np.sum(a))
print("Sum of all elements is:",np.sum(b))
print("Sum of all elements is:",np.sum(c))

# mean of all the elements in the array
print("Mean of all elements is:", np.mean(a))
print("Mean of all elements is:", np.mean(b))
print("Mean of all elements is:", np.mean(c))

# median of all the elements in the array
print("Median of all elements is:", np.median(a))
print("Median of all elements is:", np.median(b))
print("Median of all elements is:", np.median(c))

# minimum of all the elements in the array
print("Minimum of all elements is:", np.min(a))
print("Minimum of all elements is:", np.min(b))
print("Minimum of all elements is:", np.min(c))

# maximum of all the elements in the array
print("Maximum of all elements is:", np.max(a))
print("Maximum of all elements is:", np.max(b))
print("Maximum of all elements is:", np.max(c))

# variance of all the elements in the array
print("Variance of all elements is:", np.var(a))
print("Variance of all elements is:", np.var(b))
print("Variance of all elements is:", np.var(c))

# standard deviation of all the elements in the array
print("Standard Deviation of all elements is:", np.std(a))
print("Standard Deviation of all elements is:", np.std(b))
print("Standard Deviation of all elements is:", np.std(c))

Sum of all elements is: 7
Sum of all elements is: 8
Sum of all elements is: 7
Mean of all elements is: 2.3333333333333335
Mean of all elements is: 2.6666666666666665
Mean of all elements is: 2.3333333333333335
Median of all elements is: 2.0
Median of all elements is: 2.0
Median of all elements is: 2.0
Minimum of all elements is: 1
Minimum of all elements is: 2
Minimum of all elements is: 1
Maximum of all elements is: 4
Maximum of all elements is: 4
Maximum of all elements is: 4
Variance of all elements is: 1.5555555555555554
Variance of all elements is: 0.8888888888888888
Variance of all elements is: 1.5555555555555554
Standard Deviation of all elements is: 1.247219128924647
Standard Deviation of all elements is: 0.9428090415820634
Standard Deviation of all elements is: 1.247219128924647


# BROADCASTING

In [82]:
import numpy as np
a = np.array([[0, 0, 0], [1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

b = np.array([0, 1, 2])
print(b)

print(a + b)

[[0 0 0]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2]
[[ 0  1  2]
 [ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


# ARRAY MANIPULATION

In [84]:
# Concatenation of two arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print("Concatenation of two arrays :", np.concatenate((a,b)))

Concatenation of two arrays : [ 1  2  3  4  5  6  7  8  9 10]


In [86]:
c = np.array([10, 20, 30])
d = np.array([40, 50, 60])

print("Concatenation of two arrays :", np.concatenate((c,d)))

Concatenation of two arrays : [10 20 30 40 50 60]


In [87]:
print("Concatenation of two arrays :", np.concatenate((a,c)))

Concatenation of two arrays : [ 1  2  3  4  5 10 20 30]


In [88]:
print("Concatenation of two arrays :", np.concatenate((b,d)))

Concatenation of two arrays : [ 6  7  8  9 10 40 50 60]


In [89]:
print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [92]:
# stack arrays row wise vertically
print(np.vstack((a,b)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [93]:
# stack arrays row wise horizontally
print(np.hstack((a,b)))

[ 1  2  3  4  5  6  7  8  9 10]


In [94]:
# stacking arrays column wise
print(np.column_stack((a,b)))

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [95]:
print(np.column_stack((c,d)))

[[10 40]
 [20 50]
 [30 60]]


In [96]:
print(np.column_stack((d,c)))

[[40 10]
 [50 20]
 [60 30]]


In [99]:
# stack the arrays vertically
print(np.vstack((c,d)))

[[10 20 30]
 [40 50 60]]


In [101]:
# stack the arrays horizontally
print(np.hstack((c,d)))

[10 20 30 40 50 60]


# SPLITTING THE ARRAY

In [131]:
x = np.arange(16)
print(x)
# reshape the array into 4 * 4 dimensions
ans = x.reshape(4,4)
print(ans)

# split the array horizontally from position 2
res = np.hsplit(ans,2)
print(res)

# split the array horizontally in the last column
ans = np.hsplit(ans, np.array([3]))
print(ans)

# split array horizontally in three seperate columns
print(x)
print(np.hsplit(x, np.array([2, 3])))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[array([0, 1]), array([2]), array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]
