# NUMPY
It is a mathematical function that can perform matrices and array calculations.

In [1]:
import numpy as np

# CREATION OF 1-DIMENSIONAL ARRAY

In [2]:
a = [1,2,3,4,5]
# convert list into numpy array
z = np.array(a)
print(z)

[1 2 3 4 5]


In [3]:
# type of the numpy array
print(type(z))

<class 'numpy.ndarray'>


In [4]:
# size of the numpy array
print(z.size)

5


In [5]:
# shape of the numpy array
print(z.shape)

(5,)


In [6]:
# No of dimensions in the numpy array
print(z.ndim)

1


# ANOTHER WAY OF CREATION OF 1-DIMENSIONAL ARRAY

In [7]:
h = np.asarray(a)
print(h)

[1 2 3 4 5]


In [8]:
print(h)

# type of array
print(type(h))

# dimensions of array
print(h.ndim)

# size of the array
print(h.size)

# shape of the array
print(h.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
5
(5,)


# CREATION OF 2 DIMENSIONAL ARRAY

In [10]:
import numpy as np
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
# type of the numpy array
print(type(x))

<class 'numpy.ndarray'>


In [12]:
# shape of the numpy array
print(x.shape)

(2, 5)


In [13]:
# size of the numpy array
print(x.size)

10


In [14]:
# dimensions of the numpy array
print(x.ndim)

2


# INITIALIZATION OF NUMPY ARRAY

In [16]:
# zeros = It is used to initialize the numpy array with zeros with the given dimensions.
import numpy as np
x = np.zeros((6,7), dtype = 'int')

In [17]:
print(x)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [18]:
y = np.zeros((8,9), dtype = 'float')
print(y)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [19]:
# ones = It is used to initialize the numpy array with ones with the given number of dimensions.
a = np.ones((2,3), dtype = 'int')
print(a)

[[1 1 1]
 [1 1 1]]


In [20]:
b = np.ones((3,4), dtype = 'float')
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# ARRANGING THE NUMEBRS OF X AND Y WITH THE INTERVAL OF Z

In [22]:
import numpy as np
z = np.arange(2,20,2)
print(z)
print(type(z))

[ 2  4  6  8 10 12 14 16 18]
<class 'numpy.ndarray'>


In [23]:
t = np.arange(2,100,2)
print(t)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


# ARRANGING Z BETWEEN X AND Y

In [24]:
import numpy as np
x = np.linspace(2,20,10)
print(x)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [25]:
y = np.linspace(2,10,9)
print(y)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [26]:
z = np.linspace(5,10,20)
print(z)

[ 5.          5.26315789  5.52631579  5.78947368  6.05263158  6.31578947
  6.57894737  6.84210526  7.10526316  7.36842105  7.63157895  7.89473684
  8.15789474  8.42105263  8.68421053  8.94736842  9.21052632  9.47368421
  9.73684211 10.        ]


In [27]:
# even numbers from 0 to 10
even = np.linspace(0,10,6)
print(even)

[ 0.  2.  4.  6.  8. 10.]


# FILLING SAME NUMBERS IN THE ARRAY OF DIMENSIONS X * Y

In [28]:
import numpy as np
x = np.full((3,4), 10)
print(x)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [29]:
y = np.full((6,7), 12)
print(y)

[[12 12 12 12 12 12 12]
 [12 12 12 12 12 12 12]
 [12 12 12 12 12 12 12]
 [12 12 12 12 12 12 12]
 [12 12 12 12 12 12 12]
 [12 12 12 12 12 12 12]]


In [30]:
z = np.full((3,4),19)
print(z)

[[19 19 19 19]
 [19 19 19 19]
 [19 19 19 19]]


# FILLING RANDOM NUMBERS IN THE ARRAY OF DIMENSIONS X * Y

In [31]:
import numpy as np
x = np.random.random((3,4))
print(x)

[[0.55399857 0.22575679 0.44913228 0.07004671]
 [0.72916107 0.11781583 0.58393835 0.9336188 ]
 [0.53685819 0.01286078 0.35696286 0.59332436]]


In [32]:
y = np.random.random((7,8))
print(y)

[[0.66162062 0.35207244 0.41293345 0.91816771 0.44010595 0.6407155
  0.26071122 0.18143202]
 [0.68656765 0.36074118 0.00166083 0.4038593  0.1231154  0.86450491
  0.87385235 0.59580088]
 [0.38533221 0.62643821 0.27704753 0.34679217 0.64396294 0.03843873
  0.81979929 0.65361808]
 [0.12798023 0.24818088 0.76149465 0.75596303 0.32174231 0.59722269
  0.51479964 0.72281945]
 [0.33766876 0.77865271 0.2520282  0.07736911 0.43999098 0.76781217
  0.46880407 0.3798005 ]
 [0.73969809 0.32739484 0.93230108 0.99294586 0.10519299 0.40467582
  0.40496025 0.65559941]
 [0.02869861 0.67696098 0.87410054 0.19493514 0.66212632 0.27663179
  0.73318096 0.63121426]]


In [33]:
c = np.random.random((8,6))
print(c)

[[0.15196388 0.91926497 0.85870014 0.29651249 0.83566046 0.02982473]
 [0.71980752 0.23267394 0.63014317 0.68692822 0.74019677 0.78438889]
 [0.04464522 0.43963651 0.27154467 0.62745461 0.14794919 0.18979182]
 [0.25825582 0.61278272 0.70841881 0.06100465 0.23341641 0.9053179 ]
 [0.48091743 0.03396879 0.54326634 0.46542968 0.84455312 0.19231639]
 [0.38298633 0.59938058 0.89506452 0.88424113 0.28100763 0.11059111]
 [0.63262098 0.45081041 0.22204545 0.52064917 0.63788672 0.90345329]
 [0.4801234  0.70955899 0.69894791 0.45595425 0.53906341 0.87547751]]


# INSPECTING THE NUMPY ARRAY

In [34]:
# shape() = It returns the number of rows and columns in the array
x = np.array([1,2,3,4,5])
print(x.shape)

(5,)


In [35]:
x = np.array([[1,2,3],[4,5,6]])
print(x.shape)

(2, 3)


In [37]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
print(x.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


# RESIZING THE ARRAY

In [40]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
# reshape the array
ans = x.reshape((4,3))
print(ans)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
# reshape the array
ans = x.reshape((6,2))
print(ans)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [43]:
ans = x.reshape((12,1))
print(ans)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [44]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [45]:
# reshape 
print(x.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [46]:
print(x.reshape(1,6))

[[1 2 3 4 5 6]]


In [47]:
print(x.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# DIMENSIONS OF THE ARRAY

In [53]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(x)

print("Shape of the array is:", x.shape)
print("Size of the array is:", x.size)
print("Dimensions of the array is:", x.ndim)

[[1 2 3]
 [4 5 6]]
Shape of the array is: (2, 3)
Size of the array is: 6
Dimensions of the array is: 2


In [56]:
x = np.arange(1,20,2)
print(x)
# reshape the array into the dimension of 5,2
z = x.reshape((5,2))
print(z)

print("Shape of the array is:", z.shape)
print("Size of the array is:", z.size)
print("Dimensions of the array is:", z.ndim)

[ 1  3  5  7  9 11 13 15 17 19]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]
Shape of the array is: (5, 2)
Size of the array is: 10
Dimensions of the array is: 2


# RETURN THE NUMBER OF ELEMENTS IN THE ARRAY

In [63]:
x = np.arange(1,20,2)
print(x)

print("Number of elements in the array is:", x.size)
print("Data Type of this array is:", x.dtype)

[ 1  3  5  7  9 11 13 15 17 19]
Number of elements in the array is: 10
Data Type of this array is: int64


In [64]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)


print("Number of elements in the array is:", x.size)
print("Data Type of this array is:", x.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Number of elements in the array is: 12
Data Type of this array is: int64


In [65]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)


print("Number of elements in the array is:", x.size)
print("Data Type of this array is:", x.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Number of elements in the array is: 9
Data Type of this array is: int64


In [66]:
a = np.arange(10,20,2)
print(a)


print("Number of elements in the array is:", a.size)
print("Data Type of this array is:", a.dtype)

[10 12 14 16 18]
Number of elements in the array is: 5
Data Type of this array is: int64


In [67]:
b = np.arange(29)
print(b)


print("Number of elements in the array is:", b.size)
print("Data Type of this array is:", b.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28]
Number of elements in the array is: 29
Data Type of this array is: int64


# INDEXING AND SLICING IN NUMPY ARRAY

In [68]:
a = ['m','o','n','t','y','','p','y','t','h','o','n']
print(a)

['m', 'o', 'n', 't', 'y', '', 'p', 'y', 't', 'h', 'o', 'n']


In [70]:
print(a[0:5])
print(a[6:])

['m', 'o', 'n', 't', 'y']
['p', 'y', 't', 'h', 'o', 'n']


In [71]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
print(x[0:1,0:3])
print(x[0:1,1:3])
print(x[0:2,1:3])
print(x[1:3,1:])

[[1 2 3]]
[[2 3]]
[[2 3]
 [5 6]]
[[5 6]
 [8 9]]
